apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  plugins:
    metric:
      - name: argoproj-labs/metric-ai
        location: https://github.com/kdubois/rollouts-plugin-metric-ai/releases/download/v0.1.8/rollouts-plugin-metric-ai-linux-amd64
    trafficManagement: []
