apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  roles:
  - name: read-only
    description: Read-only privileges to system project
    policies:
    - p, proj:system:read-only, applications, get, system/*, allow
    - p, proj:system:read-only, applications, list, system/*, allow
    groups:
    - system:authenticated
  - name: admin
    description: Admin privileges to system project
    policies:
    - p, proj:system:admin, applications, *, system/*, allow
    groups:
    - system:cluster-admins
    - cluster-admins
