apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  roles:
  - name: read-only
    description: Read-only privileges to workloads project
    policies:
    - p, proj:workloads:read-only, applications, get, workloads/*, allow
    - p, proj:workloads:read-only, applications, list, workloads/*, allow
    groups:
    - system:authenticated
  - name: admin
    description: Admin privileges to workloads project
    policies:
    - p, proj:workloads:admin, applications, *, workloads/*, allow
    groups:
    - system:cluster-admins
    - cluster-admins
