apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus-demo

resources:
- namespace.yaml
- service-canary.yaml
- service-stable.yaml
- rollout.yaml
- analysistemplate-ai-agent.yaml
- route.yaml
- plugin-rbac.yaml
- rbac.yaml
