apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ai-analysis
spec:
  args:
  - name: stable-pod-label
    value: app=rollouts-demo,revision=stable
  - name: canary-pod-label
    value: app=rollouts-demo,revision=canary
  metrics:
  - name: ai-log-analysis
    provider:
      plugin:
        argoproj-labs/metric-ai:
          model: gemini-2.0-flash-exp
          stablePodLabel: "{{args.stable-pod-label}}"
          canaryPodLabel: "{{args.canary-pod-label}}"
          baseBranch: main
          githubUrl: https://github.com/kdubois/progressive-delivery
          extraPrompt: "Focus on error rates and performance. This is a critical production deployment."


