apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus-demo

resources:
- namespace.yaml
- service-canary.yaml
- service-stable.yaml
- rollout.yaml
- analysistemplate-ai-agent.yaml
- route.yaml
- plugin-rbac.yaml
- rbac.yaml

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Rollout
      name: argo-rollouts-quarkus-demo
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: argo-rollouts-quarkus-demo
      spec:
        template:
          spec:
            containers:
            - name: argo-rollouts-quarkus-demo
              image: quay.io/kevindubois/argo-rollouts-quarkus-demo:1.0.1
              env:
              - name: SCENARIO_MODE
                value: "failure"
              - name: ROLLOUT_NAME
                value: "argo-rollouts-quarkus-demo"
              - name: ROLLOUT_NAMESPACE
                value: "argo-rollouts-quarkus-demo"

